package org.ymx.rig;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Builds the tune and the expected result the Hatari harness is assembled
 * with. Packs a synthetic YM6 tune with the real packer and writes
 * ymxdata.inc: the frame count, the ring size, and the checksum of
 * everything the sound chip should hold after every frame - computed here,
 * from the YM data, with no knowledge of how the player works.
 *
 * <p>{@code ymx/test/run.sh} runs this before assembling the harness.
 */
final class GenData {

    private static final int FRAMES = 1500;
    private static final int RING = 960;
    private static final int CHUNK = 24;
    private static final int EXTRA = 200;   // frames played past the end,
                                            // through the restart
    private GenData() {}

    /** Fold what a YM2149 would read back after each frame into one long.
     * Registers keep their value until written again, which makes R13
     * interesting: on a frame that says "leave the envelope alone" the chip
     * still reads back the shape from an earlier frame. */
    static long chipChecksum(List<GenYm.ChipState> states) {
        long checksum = 0;
        for (GenYm.ChipState state : states) {
            for (int value : state.registers()) {
                checksum = ((checksum << 1) & 0xFFFFFFFFL) | (checksum >>> 31);
                checksum ^= value;
            }
        }
        return checksum;
    }

    public static void main(String[] args) throws IOException {
        Path here = Rig.REPO.resolve("ymx").resolve("test");
        byte[][] source = GenYm.registers(FRAMES);
        Path tune = here.resolve("tune.ym");
        Files.write(tune, GenYm.ym6File(FRAMES, source));
        Path packed = here.resolve("tune.ymx");
        Rig.run(List.of("java", "-ea", "-cp", Rig.CLASSES.toString(),
                "org.ym6.Ymx", "-f", "-n" + RING, "-c" + CHUNK, "-k1",
                tune.toString(), packed.toString()));

        int played = FRAMES + EXTRA;
        long checksum = chipChecksum(GenYm.chipStates(FRAMES, source, true, 0, played));
        // The player reports a wrap on the frame that ends the tune, so
        // count the times the last frame is played, not the times frame 0 is.
        int wraps = 0;
        for (int frame : GenYm.frameOrder(FRAMES, 0, true, played)) {
            if (frame == FRAMES - 1) {
                wraps++;
            }
        }
        Files.writeString(here.resolve("ymxdata.inc"), String.format("""
                ; Generated by the rig - do not edit.
                ; A synthetic %d-frame tune that starts over at the end, packed by the
                ; Java YMX tool, plus the checksum of the sound chip's contents after each of
                ; the %d frames the harness plays and how often the tune goes round.
                YMX_FRAMES  equ     %d
                YMX_PLAY    equ     %d
                YMX_WRAPS   equ     %d
                RING_SIZE   equ     %d
                YMX_CHUNK   equ     %d
                YMX_SUM     equ     $%08X

                        .data
                        even
                song:
                        incbin  "tune.ymx"
                        even
                """, FRAMES, played, FRAMES, played, wraps, RING, CHUNK,
                checksum), StandardCharsets.ISO_8859_1);
        System.out.println("tune.ymx: " + Files.size(packed) + " bytes, "
                + FRAMES + " frames, " + RING + "-byte rings, checksum "
                + String.format("$%08X", checksum));
    }
}
