#!/usr/bin/env python3
"""Builds the tune and the expected result the Hatari harness is assembled with.

Packs a synthetic YM6 tune with the real Java packer and writes ymxdata.inc:
the frame count, the ring size, and the checksum of everything the sound chip
should hold after every frame - computed here, from the YM data, with no
knowledge of how the player works.

    python3 ymx/test/gendata.py
"""
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
CLASSES = REPO / 'target' / 'classes'

sys.path.insert(0, str(HERE))
import gen_ym                                                       # noqa: E402

FRAMES = 1500
RING = 960
CHUNK = 24
LOOP = 601                  # deliberately not a multiple of CHUNK
EXTRA = 200                 # frames played past the end, through the loop


def chip_checksum(states) -> int:
    """Fold what a YM2149 would read back after each frame into one long.

    Registers keep their value until written again, which is what makes R13
    interesting: on a frame that says "leave the envelope alone" the chip still
    reads back the shape from an earlier frame.
    """
    checksum = 0
    for state, _ in states:
        for value in state:
            checksum = ((checksum << 1) & 0xFFFFFFFF) | (checksum >> 31)
            checksum ^= value
    return checksum


def main() -> int:
    if not CLASSES.exists():
        raise SystemExit('target/classes is missing; run `mvn compile` first')

    source = gen_ym.registers(FRAMES)
    tune = HERE / 'tune.ym'
    tune.write_bytes(gen_ym.ym6_file(FRAMES, source, loop_frame=LOOP))
    packed = HERE / 'tune.ymx'
    subprocess.run(['java', '-ea', '-cp', str(CLASSES), 'org.ym6.Ymx', '-f',
                    f'-n{RING}', f'-c{CHUNK}', '-k1', f'-l{LOOP}', str(tune), str(packed)],
                   check=True, capture_output=True)

    played = FRAMES + EXTRA
    states = gen_ym.chip_states(FRAMES, source, LOOP, played)
    checksum = chip_checksum(states)
    # The player reports a wrap on the frame that ends the tune, so count the
    # times the last frame is played, not the times the loop frame is.
    wraps = sum(1 for frame in gen_ym.frame_order(FRAMES, LOOP, played)
                if frame == FRAMES - 1)
    (HERE / 'ymxdata.inc').write_text(f"""; Generated by ymx/test/gendata.py - do not edit.
; A synthetic {FRAMES}-frame tune looping at frame {LOOP}, packed by the Java
; YMX tool, plus the checksum of the sound chip's contents after each of the
; {played} frames the harness plays and how often the tune goes round.
YMX_FRAMES  equ     {FRAMES}
YMX_PLAY    equ     {played}
YMX_WRAPS   equ     {wraps}
RING_SIZE   equ     {RING}
YMX_CHUNK   equ     {CHUNK}
YMX_SUM     equ     ${checksum:08X}

        .data
        even
song:
        incbin  "tune.ymx"
        even
""")
    print(f'tune.ymx: {packed.stat().st_size} bytes, {FRAMES} frames, '
          f'{RING}-byte rings, checksum ${checksum:08X}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
