using System;
using System.Collections.Generic;
using System.IO;

namespace Rig
{
    /// <summary>
    /// Builds the tune and the expected result the Hatari harness is
    /// assembled with, ported from the Java rig's GenData: a synthetic YM6
    /// tune packed with the real packer, and ymxdata.inc with the frame
    /// count, the ring size, and the checksum of everything the sound chip
    /// should hold after every frame - computed here, from the YM data, with
    /// no knowledge of how the player works.
    /// </summary>
    public static class GenData
    {
        private const int Frames = 1500;
        private const int Ring = 960;
        private const int Chunk = 24;
        private const int Extra = 200;      // frames played past the end,
                                            // through the restart

        /// <summary>Fold what a YM2149 would read back after each frame into
        /// one long; on a frame that says "leave the envelope alone" the
        /// chip still reads back the shape from an earlier frame.</summary>
        public static long ChipChecksum(List<GenYm.ChipState> states)
        {
            long checksum = 0;
            foreach (GenYm.ChipState state in states)
            {
                foreach (int value in state.Registers)
                {
                    checksum = ((checksum << 1) & 0xFFFFFFFF) | (checksum >>> 31);
                    checksum ^= value;
                }
            }
            return checksum;
        }

        public static void Main(string[] args)
        {
            string here = Path.Combine(Rig.Repo, "ymx", "test");
            byte[][] source = GenYm.Registers(Frames);
            string tune = Path.Combine(here, "tune.ym");
            File.WriteAllBytes(tune, GenYm.Ym6File(Frames, source));
            string packed = Path.Combine(here, "tune.ymx");
            List<string> command = Rig.OwnTool("ymx");
            command.AddRange(new[] {"-f", "-n" + Ring, "-c" + Chunk, "-k1",
                    tune, packed});
            Rig.Run(command);

            int played = Frames + Extra;
            long checksum = ChipChecksum(GenYm.ChipStates(Frames, source, true, 0,
                    played));
            // The player reports a wrap on the frame that ends the tune, so
            // count the times the last frame is played, not the times frame
            // 0 is.
            int wraps = 0;
            foreach (int frame in GenYm.FrameOrder(Frames, 0, true, played))
            {
                if (frame == Frames - 1)
                {
                    wraps++;
                }
            }
            File.WriteAllText(Path.Combine(here, "ymxdata.inc"), string.Format(
                    "; Generated by the rig - do not edit.\n"
                    + "; A synthetic {0}-frame tune that starts over at the end, packed by the\n"
                    + "; Java YMX tool, plus the checksum of the sound chip's contents after each of\n"
                    + "; the {1} frames the harness plays and how often the tune goes round.\n"
                    + "YMX_FRAMES  equ     {0}\n"
                    + "YMX_PLAY    equ     {1}\n"
                    + "YMX_WRAPS   equ     {2}\n"
                    + "RING_SIZE   equ     {3}\n"
                    + "YMX_CHUNK   equ     {4}\n"
                    + "YMX_SUM     equ     ${5:X8}\n"
                    + "\n"
                    + "        .data\n"
                    + "        even\n"
                    + "song:\n"
                    + "        incbin  \"tune.ymx\"\n"
                    + "        even\n",
                    Frames, played, wraps, Ring, Chunk, checksum));
            Console.WriteLine("tune.ymx: " + new FileInfo(packed).Length
                    + " bytes, " + Frames + " frames, " + Ring
                    + "-byte rings, checksum " + string.Format("${0:X8}", checksum));
        }
    }
}
